using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

// constrctctor types

// Constructors can be parameterless or parameterized. They can be implicit or explicit. Implicit are generated by default by compiler. explicit are defined by programmer.
// Implicit constructors are parameterless. Explicit can be both .

namespace FirstProject
{
    internal class ConstructorDemo
    {   
        // these variables will be automatically initialized in implicit constructor by compiler.
        int i; bool b;

        static void Main()
        {
            // to access i and b values to see how they are initialized in implicit constructor we  create an instance of the class ConstructorDemo

            // we are explicitly calling the constructor . If you hover in ConstructorDemo() youll see ConstructorDemo.ConstructorDemo(). 
            //The second one is constructor. Here we call the implicit constructor defined by compiler during runtime
            ConstructorDemo c = new ConstructorDemo();
            Console.WriteLine("Value of i in implicit constructor " + c.i);
            Console.WriteLine("Value of i in implicit constructor " + c.b);

        }

        
    }
}
